# Generated by Django 6.1.1 on 2026-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_details',
            field=models.TextField(blank=True),
        ),
    ]
